# Generated by Django 4.1.3 on 2022-11-01 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slovar', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rus',
            new_name='Words',
        ),
    ]
