# Generated by Django 4.1.3 on 2022-11-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovar', '0002_rename_rus_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='tag',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
