# Generated by Django 4.1.3 on 2022-11-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slovar', '0004_tags_alter_words_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='slov',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
